#! /usr/bin/env python3
''' importing sys for input through shell and capitals module from the python package '''
import sys
import package.capitals as c

''' if sys has been given an argument through the shell by user its gonna call back to check capital function from the module and gave back the results  '''

if len(sys.argv) >= 1:
    input = sys.argv[1]
    print(c.check_capital(input))
else:
    print("pls insert any input")
    exit()
